spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:21336/railway

spring.datasource.username=root
spring.datasource.password=lQDYfHtQJqCKLvZtBPoqchBqVOFcYKXM

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}